
tasks:
  - name: Setup
    init: npm install
    command: npm run start
ports:
  - port: 7000
    onOpen: open-preview
vscode:
  extensions:
    - esbenp.prettier-vscode
    - dbaeumer.vscode-eslint
    - github.vscode-pull-request-github
